### ISSUE TITLE
unable to locate pkgs.txt

### ISSUE THREAD

**Issue by ninjaijr** [puxplaying/releasecompare#2]
when the tool tries to pull the pkgs.txt the redirect attempt to find it but fails then it prompts me to enter the url... using the link it points to the archives. i am unable to locate the current pkgs.txt for comparison

**Comment by puxplaying** [comment]
Hi there, thanks for the report!
You're absolutely right as i forgot to fix it in this repo.
In the mean time, please take a look at [toolbox](https://github.com/puxplaying/toolbox), which is available as bmenu in the Manjaro repo. It has a working version of releasecompare (option 9).

I will fix this in the next couple days.

**Comment by puxplaying** [comment]
The problem should be fixed with the latest update.  
65c533e09f929f951d749eca48b68c039c749412
